### ISSUE TITLE
io.dapr.exceptions.DaprException: UNAVAILABLE: io exception

### ISSUE THREAD

**Issue by tiankanghello** [dapr/java-sdk#612]
When I use dapr's sub / pub to publish a topic, I fail. I don't know why I report an error. The specific information of the error is

> 

java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_281]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715) ~[na:1.8.0_281]
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[grpc-netty-shaded-1.33.1.jar:1.33.1]
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[grpc-netty-shaded-1.33.1.jar:1.33.1]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702) ~[grpc-netty-shaded-1.33.1.jar:1.33.1]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[grpc-netty-shaded-1.33.1.jar:1.33.1]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[grpc-netty-shaded-1.33.1.jar:1.33.1]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[grpc-netty-shaded-1.33.1.jar:1.33.1]
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[grpc-netty-shaded-1.33.1.jar:1.33.1]
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[grpc-netty-shaded-1.33.1.jar:1.33.1]
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[grpc-netty-shaded-1.33.1.jar:1.33.1]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_281]

**Comment by mthmulders** [comment]
My first guess would be that the application fails to connect to the Dapr sidecar. Are you sure you have a Dapr sidecar running? How did you start your application?

**Comment by tiankanghello** [comment]
I rechecked my configuration. It's true that I didn't connect to dapr, but after I connected to dapr, I reported another problem when publishing the theme,
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.dapr.exceptions.DaprException: INVALID_ARGUMENT: pubsub create not found] with root cause

io.grpc.StatusRuntimeException: INVALID_ARGUMENT: pubsub create not found
	at io.grpc.Status.asRuntimeException(Status.java:535) ~[grpc-api-1.39.0.jar:1.39.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) ~[grpc-stub-1.39.0.jar:1.39.0]
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463) ~[grpc-core-1.39.0.jar:1.39.0]
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427) ~[grpc-core-1.39.0.jar:1.39.0]
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460) ~[grpc-core-1.39.0.jar:1.39.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553) ~[grpc-core-1.39.0.jar:1.39.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68) ~[grpc-core-1.39.0.jar:1.39.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739) ~[grpc-core-1.39.0.jar:1.39.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718) ~[grpc-core-1.39.0.jar:1.39.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.39.0.jar:1.39.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.39.0.jar:1.39.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_281]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_281]

**Comment by mthmulders** [comment]
I guess that the code wants to use a pub/sub that is not there. Could you please show the code that you use to publish the event, as well as the Dapr component configuration you're using?

**Comment by tiankanghello** [comment]
I have solved this problem. Thank you very much for your answer. When publishing and subscribing, the published pubsubname must be the metadata name we started the dapr component. Just keep the two consistent.
If I use two pubsubnames, should I start two pub / sub components
