### ISSUE TITLE
Actor is permanently blocked when registering reminders with MongoDB

### ISSUE THREAD

**Issue by MoeweX** [dapr/java-sdk#656]
## Expected Behavior

When I ask an actor to register multiple reminders, I want him to register all these reminders.

## Actual Behavior

The actors stops doing anything after the first reminder registration. This also blocks the application that invoked the actor's method for reminder registration.  After a couple of minutes, an exception appears that also kills the application, see output: The first line is from the registerReminders method below:

```bash
== APP == Created reminder 0
== APP == 2021-11-17 16:56:37,537 {HH:mm:ss.SSS} [http-nio-3001-exec-4] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] threw exception
== APP == io.grpc.StatusRuntimeException: UNKNOWN: could not parse actor reminders: json: cannot unmarshal array into Go value of type actors.Reminder
== APP == 	at io.grpc.Status.asRuntimeException(Status.java:535)
== APP == 	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
== APP == 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
== APP == 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
== APP == 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
== APP == 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
== APP == 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
== APP == 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
== APP == 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
== APP == 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
== APP == 	at java.base/java.lang.Thread.run(Thread.java:829)
== APP == 2021-11-17 16:56:37,537 {HH:mm:ss.SSS} [http-nio-3001-exec-4] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: java.lang.reflect.InvocationTargetException] with root cause
== APP == io.grpc.StatusRuntimeException: UNKNOWN: could not parse actor reminders: json: cannot unmarshal array into Go value of type actors.Reminder
== APP == 	at io.grpc.Status.asRuntimeException(Status.java:535)
== APP == 	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
== APP == 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
== APP == 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
== APP == 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
== APP == 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
== APP == 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
== APP == 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
== APP == 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
== APP == 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
== APP == 	at java.base/java.lang.Thread.run(Thread.java:829)
```

## Steps to Reproduce the Problem

Tested with Dapr 1.5.0., I ran the same workload with Redis locally and CosmosDB; both worked fine. Only for MongoDB I have this issue.

```java
// This method is invoked from the outside after the actor was created the first time.
@Override
public double registerReminders(int numberOfReminders) {
  Duration dueTime = Duration.ofDays(1);
  Duration period = Duration.ofDays(1);
  List<Long> registrationTimes = new ArrayList<>(numberOfReminders);

  for (int i = 0; i < numberOfReminders; i++) {
    long start = System.nanoTime();
    super.registerReminder("benchmark-" + i, getId() + "-" + i, dueTime, period).block();
    registrationTimes.add(System.nanoTime() - start);
    System.out.println("Created reminder " + i);
  }

  return registrationTimes.stream().mapToDouble(l -> l).average().orElseThrow();
}
```

I use Mongo Atlas, my config looks like so:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.mongodb
  version: v1
  metadata:
    - name: server
      value: REMOVED
    - name: databaseName
      value: daprStore
    - name: collectionName
      value: daprCollection
    - name: operationTimeout
      value: 10s
    - name: actorStateStore
      value: "true"
```

## Release Note

RELEASE NOTE:

**Comment by mukundansundar** [comment]
@artursouza Based on the description, I think this needs to be moved to the components-contrib repo.

**Comment by MoeweX** [comment]
I am fine with it being transferred, but I do not have the rights for this: https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository
