### ISSUE TITLE
Support Dapr Java SDK with JDK 17 and Spring boot version 3.0

### ISSUE THREAD

**Issue by rahulpoddar-fyndna** [dapr/java-sdk#886]
Dapr java SDK is available with JDK 11 and uses spring boot version 2.7.8 as of now. Spring boot has the release latest version 3.0.
In order to move the Spring 3.0 the library has to be supported with JDK 17.

With JDK 17, the java enterprise edition has moved to Jakarta enterprise edition and this needs some code changes as well.Specifically all the javax namespace has moved to Jakarta namespace.

We plan to move to JDK 17 along with Spring Boot 3.0.  

Dapr SDK provides sdk-springboot library to support development using spring boot. As of now this library uses spring boot version 2.7.8.  sdk-springboot library needs to be supported with latest version of spring boot 3.0.

After successfully moving to JDK 17 and Spring boot 3.0, we will adopt Spring native.

**Comment by yaron2** [comment]
cc @artursouza

**Comment by artursouza** [comment]
There are users already reporting wanting to use Dapr's SDK with Spring Boot 3.0, like in https://github.com/dapr/java-sdk/issues/815

We need to complete this migration but have not started the work yet - I am looking for someone to get this work done. I can accept contribution from the community on this as well.

**Comment by krizsan** [comment]
I may have something in connection to this issue here:
https://github.com/krizsan/dapr-java-sdk
Work in progress and first time contributing, so any feedback is welcome.

**Comment by skyao** [comment]
I have one question about the target of this change:  after this update, should dapr java sdk 

- supports only jdk17 and spring boot 3.0
- or supports both jdk17 with spring boot 3.0 and jdk11 with spring boot 2.x

I think the answer should be the second, and also I found some changes in PR to support this idea: 

```yaml
      matrix:
 -       java: [ 11, 13, 15, 16 ]
 -       spring-boot-version: [ 2.7.8 ]
 +       java: [ 11, 13, 15, 16, 17 ]
 +      spring-boot-version: [ 2.7.8, 3.1.2 ]
```

and also :

```yaml
          - java: 11
            spring-boot-version: 2.3.6.RELEASE
            experimental: false
+          - java: 17
+           spring-boot-version: 3.1.2
+          experimental: false
```

It seems that we will "ADD" support for java 17 and spirng boot 3.0 and still "keep" support for java 11+ and spring boot 2.

But I found that in the root pom.xml, the value of property springboot.version has simply changed from 2.7.8 to 3.1.2: 

```xml
-    <springboot.version>2.7.8</springboot.version>
+    <springboot.version>3.1.2</springboot.version>
```

And when I used jdk11 to execute maven command like `mvn compile`: 

```bash
$ sdk current java 
Using java version 11.0.20-zulu

# mvn compile
......
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project dapr-sdk-springboot: Compilation failure
[ERROR] Could not load processor class file due to 'org/springframework/boot/configurationprocessor/ConfigurationMetadataAnnotationProcessor has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0'.
```

So from content of the PR https://github.com/dapr/java-sdk/pull/894, It seems that we will "ONLY" support for java 17  with spring boot 3.

That's why I ask this question here. We must clarify or make decision about the target before we go deep into this update.

**Comment by skyao** [comment]
@artursouza  @yaron2 @krizsan please have a look at my above comments and clarify what's your target for spring boot 3.0 support.

**Comment by krizsan** [comment]
@skyao I think the above is a good suggestion given that, for example, Spring Boot 3 is using the jakarta dependencies instead of the javax dependencies and it will require additional effort to be able to compile the same project against Spring Boot 2 and Spring Boot 3, if at all possible.

**Comment by rabollin** [comment]
@skyao - Given the limitations we are running to support both JAVA 17 & 11 the approach proposed you seem to be a best option.   I think this approach may introduce some breaking changes to existing projects and can they be avoided?

**Comment by artursouza** [comment]
I agree to have a different project (artifact) for springboot3. Let's keep the current one as-is (without renaming) for backwards compatibility. I don't think there is a need to create new repositories, just new projects under the same parent pom.

So, I recommend creating dapr-springboot3.

**Comment by skyao** [comment]
> 

Hi, @artursouza , I agree with you except that can we have solution to just add dapr-springboot3 with jdk17 in the java-sdk project without upgrade the sdk of the whole project from jdk11 to jdk 17? 

> I had confirmed that both maven and gradle can't support to use different version of jdk to diffrent subprojects. 

Another solution is keeping our jdk strategy in current java-sdk project that using jdk 11 but set source and target to jdk8:

```xml
    <maven.compiler.source>8</maven.compiler.source>
    <maven.compiler.target>8</maven.compiler.target>
```

We can then using jdk 17 and also set source and target to jdk8 (or jdk11 if jdk 8 not work) .

**Comment by skyao** [comment]
I did some test and share the results to you.

First I changed the jdk version to 17 (by sdkman) , and I used jdk17 to execute `mvn compile` command in dapr java-sdk project without changing any code. 

At first it reported many errors like: 

```bash
......
     [java]   Couldn't get class info for java/lang/NumberFormatException
     [java]     java.lang.IllegalArgumentException: Unsupported class file major version 61
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:189)
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:156)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
     [java]       At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
     [java]       At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:685)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:975)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:909)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:252)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
     [java]   Couldn't get class info for java/lang/AssertionError
     [java]     java.lang.IllegalArgumentException: Unsupported class file major version 61
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:189)
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:156)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
     [java]       At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
     [java]       At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:685)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:975)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:909)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:252)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
     [java]   Couldn't get class info for java/util/Collections
     [java]     java.lang.IllegalArgumentException: Unsupported class file major version 61
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:189)
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:156)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
     [java]       At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
     [java]       At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:685)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:975)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:909)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:252)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
     [java]   Couldn't get class info for java/lang/Float
     [java]     java.lang.IllegalArgumentException: Unsupported class file major version 61
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:189)
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:156)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
     [java]       At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
     [java]       At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:685)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:975)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:909)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:252)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
     [java]   Couldn't get class info for java/util/Set
     [java]     java.lang.IllegalArgumentException: Unsupported class file major version 61
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:189)
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:156)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
     [java]       At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
     [java]       At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:685)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:975)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:909)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:252)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
     [java] Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 61
     [java]     at org.objectweb.asm.ClassReader.<init>(ClassReader.java:189)
     [java]     at org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
     [java]     at org.objectweb.asm.ClassReader.<init>(ClassReader.java:156)
     [java]     at edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
     [java]     at edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
     [java]     at edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
     [java]     at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
     [java]     at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
     [java]     at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]     at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
     [java]     at edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:685)
     [java]     at edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:975)
     [java]     at edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:909)
     [java]     at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:252)
     [java]     at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
     [java]     at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] dapr-sdk-parent 1.10.0-SNAPSHOT .................... SUCCESS [  1.040 s]
[INFO] dapr-sdk-autogen 1.10.0-SNAPSHOT ................... SUCCESS [  0.517 s]
[INFO] dapr-sdk 1.10.0-SNAPSHOT ........................... FAILURE [  1.695 s]
[INFO] dapr-sdk-actors 1.10.0-SNAPSHOT .................... SKIPPED
[INFO] dapr-sdk-workflows 0.10.0-SNAPSHOT ................. SKIPPED
[INFO] dapr-sdk-springboot 1.10.0-SNAPSHOT ................ SKIPPED
[INFO] dapr-sdk-examples 1.10.0-SNAPSHOT .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.565 s
[INFO] Finished at: 2023-08-22T09:17:53Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:4.1.4:spotbugs (spotbugs) on project dapr-sdk: Execution spotbugs of goal com.github.spotbugs:spotbugs-maven-plugin:4.1.4:spotbugs failed: Java returned: 1 -> [Help 1]
```

And then I removed the plugin of spotbugs in root pom.xml, 

```bash
mvn compile

......
[INFO] dapr-sdk-parent 1.10.0-SNAPSHOT .................... SUCCESS [  0.785 s]
[INFO] dapr-sdk-autogen 1.10.0-SNAPSHOT ................... SUCCESS [  5.076 s]
[INFO] dapr-sdk 1.10.0-SNAPSHOT ........................... SUCCESS [  1.719 s]
[INFO] dapr-sdk-actors 1.10.0-SNAPSHOT .................... SUCCESS [  0.321 s]
[INFO] dapr-sdk-workflows 0.10.0-SNAPSHOT ................. SUCCESS [  0.184 s]
[INFO] dapr-sdk-springboot 1.10.0-SNAPSHOT ................ SUCCESS [  0.170 s]
[INFO] dapr-sdk-examples 1.10.0-SNAPSHOT .................. SUCCESS [  0.745 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.523 s
[INFO] Finished at: 2023-08-22T09:20:02Z
[INFO] ------------------------------------------------------------------------
```

The jdk I used:

```bash
 java --version
java 17.0.8 2023-07-18 LTS
Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)
```

**Comment by krizsan** [comment]
@skyao I have tried to describe the changes in each commit in the commit messages in my fork. As far as I recall, the major work was upgrading dependency versions. If the Spring Boot 3 Dapr Java SDK is to be a separate project and your findings regarding the Java version, then perhaps starting afresh is a good idea.

**Comment by krizsan** [comment]
I just tried OpenRewrite using the Upgrade Spring Boot 3.1 recipe on the project and it did complete without errors as far as I can tell. However, there are additional changes made beyond what is strictly necessary for an upgrade to Spring Boot 3.1, for instance upgrade from JUnit 4 to JUnit 4. Is this something desired?
The project does need some additional modifications in order to compile and then there are a number of Spotbugs errors.
OpenRewrite configuration used:
`<profiles>
    <profile>
      <id>openrewrite</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.openrewrite.maven</groupId>
            <artifactId>rewrite-maven-plugin</artifactId>
            <version>5.4.2</version>
            <configuration>
              <activeRecipes>
                <recipe>org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_1</recipe>
              </activeRecipes>
            </configuration>
            <dependencies>
              <dependency>
                <groupId>org.openrewrite.recipe</groupId>
                <artifactId>rewrite-spring</artifactId>
                <version>5.0.7</version>
              </dependency>
            </dependencies>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>`

**Comment by krizsan** [comment]
Correct me if I am wrong, but as far as I can tell the following modules of this project need to be updated with regard to Spring Boot 3:

- examples
(has dependency to Spring Boot)
- sdk
(has test-dependecy to Spring Boot but also dependency to reactor-core which should match that of Spring Boot)
- sdk-springboot
(has dependency to Spring Boot)
- sdk-tests
(has test-dependencies to Spring Boot and reactor-core)

The following module have dependencies to the dapr-sdk module and thus I suspect that having a different Spring Boot version is not a good idea:
-  sdk-actors
(has test-dependencies to Spring Boot)

Thus I am afraid I do not see how to contain the Spring Boot 3 upgrade to one single module.

**Comment by skyao** [comment]
So from above discussion, it seems that at least we should move spring boot3 support out of dapr java sdk ( to a new repo). 

@artursouza Do you agree with this proposal?

**Comment by skyao** [comment]
@artursouza please have a look at this discussion.

**Comment by artursouza** [comment]
> So from above discussion, it seems that at least we should move spring boot3 support out of dapr java sdk ( to a new repo).
> 
> @artursouza Do you agree with this proposal?

I don't think we should have a new repo just for springboot3 code - we should find a way to have it here. It is OK if Java17 is required for dev but the artifacts (jars) should be compatible for Java 11.

**Comment by artursouza** [comment]
Is anyone working on dapr-springboot3 project? As discussed here, it can simply be a new artifact in this repo, similar to how dapr-workflow is being versioned.

**Comment by rabollin** [comment]
@skyao - FYA as this is in the priority list to solve it in 1.13 release timeframe.

**Comment by skyao** [comment]
> Is anyone working on dapr-springboot3 project? As discussed here, it can simply be a new artifact in this repo, similar to how dapr-workflow is being versioned.

Hi, Artur, please go this proposal and review it:

https://github.com/dapr/java-sdk/issues/971

After all kinds of testing and validation, I finally found a solution that looks ideal for upgrading jdk17 and springboot 3.0. You help me to see if this solution will satisfy you.

**Comment by salaboy** [comment]
We upgraded to Spring Boot 3.x : https://github.com/dapr/java-sdk/blob/9cd6db2f5d78a349cc115d75d3d144a26e777667/dapr-spring/pom.xml#L31 and the SDK as far as I know it is not using any JDK 17 features, so we are using 11, but it should be totally compatible. If someone finds an issue regarding this please create a new issue

**Comment by salaboy** [comment]
Done in 1.14. Support for JDK 17 and Spring Boot 3.4.3
