### ISSUE TITLE
Method HEAD must not have a request body

### ISSUE THREAD

**Issue by nacyolsa** [dapr/java-sdk#891]
## Expected Behavior

HEAD method should work.

## Actual Behavior

I'm trying to invoke HEAD method but I'm receiving exception `method HEAD must not have a request body.`.

```
java.lang.IllegalArgumentException: method HEAD must not have a request body.
	at okhttp3.Request$Builder.method(Request.kt:258)
	at io.dapr.client.DaprHttp.doInvokeApi(DaprHttp.java:301)
	at io.dapr.client.DaprHttp.lambda$invokeApi$0(DaprHttp.java:234)
	at reactor.core.publisher.MonoCallable.call(MonoCallable.java:72)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:127)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4444)
	at kotlinx.coroutines.reactor.MonoKt.awaitSingleOrNull(Mono.kt:47)
```

## Steps to Reproduce the Problem

```kotlin
daprClient.invokeMethod<Unit>(
            InvokeMethodRequest(
                "test",
                "test-head"
            ).apply {
                httpExtension = HttpExtension(
                    DaprHttp.HttpMethods.HEAD,
                )
                body = null
            },
            null
        )
```

Am I doing something wrong or it's some bug?

I use dapr-sdk 1.9.0 but I also tried with 1.7.1 version.

**Comment by AishwaryaBalyaya01** [comment]
We have to remove body=null, this way

daprClient.invokeMethod<Unit>(
    InvokeMethodRequest(
        "test",
        "test-head"
    ).apply {
        httpExtension = HttpExtension(
            DaprHttp.HttpMethods.HEAD
        )
    },
    null
)



As I am not able to reoslve build issues, and I know how to solve it I have mentioned the solution here!
